name: SI-VAE
target_size: !!python/tuple &target_size [128, 128]
dbatch_size: &dbatch_size 8
checkpoint_path: &checkpoint_path ./weights/phanes_miccai/sota/
#
# Experiment
#
experiment:
  name: SIVAE_new_16batch
  task: test
  weights: "./weights/phanes_miccai/sota/2023_03_28_17_08_05_730580/best_model.pt"
#  weights: './weights/phanes_miccai/sota/2023_01_31_16_11_37_011460/latest_model.pt'./weights/fast_mri/sota/2022_11_26_10_31_32_965404

#
device: cpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.soft_intro_vae_daniel
  class_name: SoftIntroVAE
  params:
    cdim: 1
    zdim: 128
    channels:
      - 64
      - 128
      - 256
      - 512
      - 512
    image_size: 128
    conditional: False
#
# Trainer
#
trainer:
  module_name: projects.ano_brain_us.SIVAETrainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 200
    loss:
      module_name: optim.losses.ln_losses
      class_name: L2
      params:
    # Optimizer
    patience: 500
    optimizer_params:
      lr: 1.0e-5 # 2.0e-4 $ orig
  # Data Loader
  data_loader:
    # IXI-T1
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: core.DataLoader
          class_name: DefaultDataset
        data_dir:
          train:
            - "E:\\Master Thesis\\iml-dl\\data\\augmented_train\\*"
          val:
            - "./data/augmented_val/*"
          test:
            - "./data/augmented_test/*"
        file_type: "*png"
        target_size: *target_size
        batch_size: 16
# Downstream tasks
downstream_tasks:
  detection:
    module_name: projects.ano_brain_us.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    global_detection: True
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          target_size: *target_size
          batch_size: *dbatch_size
          dataset_module:
            module_name: core.DataLoader
            class_name: DefaultDataset
      datasets:
        Normal_brain:
          data_dir:
            test:
              - "./data/Ventricular_segmented_clean_test/*"
        global_pathology:
          data_dir:
            test:
              - "./data/anomaly_segmented/*"
#
#  pseudo_healthy:
#    module_name: projects.23_phanes_miccai.DownstreamEvaluator
#    class_name: PDownstreamEvaluator
#    checkpoint_path: *checkpoint_path
#    global_detection: False
#    data_loader:
#      module_name: core.DataLoader
#      class_name: DefaultDataLoader
#      params:
#        args:
#          target_size: *target_size
#          batch_size: *dbatch_size
#          dataset_module:
#            module_name: data.loaders.fastmri_loader
#            class_name: FastLoader
#      datasets:
#        Normal_brain:
#          data_dir:
#            test:
#              - './data/fastMRI/splits/normal_test.csv'
