name: AAE
target_size: &target_size !!python/tuple [128, 128]
dbatch_size: &dbatch_size 100
checkpoint_path: &checkpoint_path ./weights/yigit_trial/sota/
#
# Experiment
#
experiment:
  name: AAE (Train)
  task: train # change to test for eval mode only
  weights: #'./weights/pathology/2022_11_25_15_31_40_585061/best_model.pt'
#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.aae_pidhorskyi
  class_name: AAE
  params:
    d: 64
#    extra_layers: 1 # for 64x64
    extra_layers: 2 # for 128x128
    z_dim: 256
#
# Trainer
#
trainer:
  module_name: projects.ano_brain.AAETrainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 100
    loss:
      module_name: optim.losses.ln_losses
      class_name: L2
      params:
    patience: 500
    # Optimizer
    optimizer_params:
      lr: 5.0e-4 # 2.03-3 # Orig
  # Data Loader
  data_loader:
# IXI-T1
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.loaders.fastmri_loader
          class_name: FastLoader
        data_dir:
          train:
#          - './data/CAPS_IXI/splits/ixi-t1_train_2D.csv'
#          - './data/ATLAS_2/splits/atlas_train_dummy.csv'
          - './data/CAPS_IXI/ixi_normal_train.csv'
          val:
#          - './data/ATLAS_2/splits/atlas_test.csv'
#          - './data/CAPS_IXI/splits/ixi-t1_val_2D.csv'
          - './data/fastMRI/normal_val.csv'
          test:
#          - './data/CAPS_IXI/splits/ixi-t1_val_2D.csv'
#            - './data/ATLAS_2/splits/atlas_test_dummy.csv'
          - './data/fastMRI/normal_test.csv'
        target_size: *target_size
        batch_size: 8
# Downstream tasks
downstream_tasks:
    detection:
      module_name: projects.ano_brain.DownstreamEvaluator
      class_name: PDownstreamEvaluator
      checkpoint_path: *checkpoint_path
      global_detection: True
      data_loader:
        module_name: core.DataLoader
        class_name: DefaultDataLoader
        params:
          args:
            target_size: *target_size
            batch_size: *dbatch_size
            dataset_module:
              module_name: data.loaders.fastmri_loader
              class_name: FastLoader
        datasets:
          global_pathology:
            data_dir:
              test:
                - './data/ATLAS/atlas_test_png.csv'
#
#  pseudo_healthy:
#    module_name: projects.23_phanes_miccai.DownstreamEvaluator
#    class_name: PDownstreamEvaluator
#    checkpoint_path: *checkpoint_path
#    global_detection: False
#    data_loader:
#      module_name: core.DataLoader
#      class_name: DefaultDataLoader
#      params:
#        args:
#          target_size: *target_size
#          batch_size: *dbatch_size
#          dataset_module:
#            module_name: data.loaders.fastmri_loader
#            class_name: FastLoader
#      datasets:
#        Normal_brain:
#          data_dir:
#            test:
#              - './data/fastMRI/splits/normal_test.csv'