name: ae_kl
target_size: &target_size !!python/tuple [88, 120, 128]
dbatch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path ./weights/brain_3D/sota/
#
# Experiment
#
experiment: 
  name: Morphaeus_3D_ADNI_mixeddata_adv_loss_last
  task: train
  weights: #'./weights/brain_3D/sota/2023_10_16_11_56_15_283413/best_model.pt'
#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.autoencoder_kl
  class_name: AutoencoderKL
  params:
    spatial_dims: 3
    in_channels: 1
    out_channels: 1
    num_channels:
      - 32
      - 64
      - 64
    latent_channels: 3
    num_res_blocks: 1
    norm_num_groups: 16
    attention_levels:
      - False
      - False
      - False
#
# Trainer
#
trainer:
  module_name: projects.ano_brain.AEKLTrainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 5000
    patience: 500
    # Loss
    loss:
      module_name: optim.losses.ln_losses
      class_name: L1
      params:
#    patience: 5  # Orig
    # Optimizer
    optimizer_params:
#      lr: 1.0e-4 # Orig
      lr: 1.0e-4
  # Data Loader
  data_loader:
# IXI-T1
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.loaders.brain3D_loader_ae_kl
          class_name: Brain3DLoader
        data_dir:
          train:
#          - './data/CAPS_IXI/splits/ixi-t1_train_2D.csv'
#          - './data/ATLAS_2/splits/atlas_train_dummy.csv'
          - './data/ADNI/cn_siem_3T_ww_train_registered.csv'
          val:
#          - './data/ATLAS_2/splits/atlas_test.csv'
#          - './data/CAPS_IXI/splits/ixi-t1_val_2D.csv'
          - './data/ADNI/cn_siem_3T_ww_val_registered.csv'
          test:
#          - './data/CAPS_IXI/splits/ixi-t1_val_2D.csv'
#            - './data/ATLAS_2/splits/atlas_test_dummy.csv'
          - './data/ADNI/cn_siem_3T_ww_test_registered.csv'
        target_size: *target_size
#        batch_size: 128 # Orig
        batch_size: 1
# Downstream tasks
downstream_tasks:
    detection:
      module_name: projects.ano_brain.DownstreamEvaluator_aekl
      class_name: PDownstreamEvaluator
      checkpoint_path: *checkpoint_path
      global_detection: True
      data_loader:
        module_name: core.DataLoader
        class_name: DefaultDataLoader
        params:
          args:
            target_size: *target_size
            batch_size: *dbatch_size
            dataset_module:
          module_name: data.brain3D_loader
          class_name: Brain3DLoader
        datasets:
          global_detection:
            data_dir:
              test:
                - './data/ADNI/AD_Siem_3T_WW.csv'
 
    detection2:
      module_name: projects.ano_brain.DownstreamEvaluator_aekl
      class_name: PDownstreamEvaluator
      checkpoint_path: *checkpoint_path
      global_detection2: True
      data_loader:
        module_name: core.DataLoader
        class_name: DefaultDataLoader
        params:
          args:
            target_size: *target_size
            batch_size: *dbatch_size
            dataset_module:
          module_name: data.brain3D_loader
          class_name: Brain3DLoader
        datasets:
          global_detection2:
            data_dir:
              test:
                - './data/ADNI/cn_siem_3T_ww_test_registered.csv'      
    detection3:
      module_name: projects.ano_brain.DownstreamEvaluator_aekl
      class_name: PDownstreamEvaluator
      checkpoint_path: *checkpoint_path
      global_detection2: True
      data_loader:
        module_name: core.DataLoader
        class_name: DefaultDataLoader
        params:
          args:
            target_size: *target_size
            batch_size: *dbatch_size
            dataset_module:
          module_name: data.brain3D_loader
          class_name: Brain3DLoader
        datasets:
          global_detection3:
            data_dir:
              test:
                - './data/ADNI/MCI_Siem_3T_WW.csv'                              
