name: DAE
target_size: &target_size !!python/tuple [128, 128]
dbatch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path ./weights/phanes_miccai/sota/
#
# Experiment
#
experiment:
  name: 23_MICCAI_PHANES [Synthetic]
  task: test
  weights: './weights/fast_mri/sota/2022_12_06_12_40_20_922068/best_model.pt'
#  weights:  './weights/phanes_miccai/sota/2023_01_31_16_07_58_330909/best_model.pt'
#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.dae_kascenas
  class_name: UNet
  params:
    in_channels: 1
    n_classes: 1
    norm: "group"
    up_mode: "upconv"
    depth: 4 # 4 for 128 x 128
    wf: 6 # 6 for 128x128
    padding: True
#
# Trainer
#
trainer:
  module_name: projects.23_phanes_miccai.Trainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 3000
    patience: 500
    # Transformer
    transformer:
      module_name: transforms.gaussian_noise
      class_name: GaussianNoise
      params:
        noise_std: 0.2
        noise_res: 16
    loss:
      module_name: optim.losses.ln_losses
      class_name: L1
      params:
    lr_scheduler: 'cosine'
    # Optimizer
    optimizer_params:
      lr: 1.0e-4 # 1.0e-4 # orig
  # Data Loader
  data_loader:
# IXI-T1
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.loaders.ixi_loader
          class_name: IXILoader
        data_dir:
          train:
          - './data/CAPS_IXI/splits/t1_mix_train.csv'
          val:
          - './data/CAPS_IXI/splits/ixi-t1_val_png.csv'
          test:
          - './data/CAPS_IXI/splits/ixi-t1_test_png.csv'
        target_size: *target_size
        batch_size: 8
# Downstream tasks
downstream_tasks:
#  detection:
#    module_name: projects.23_phanes_miccai.DownstreamEvaluator
#    class_name: PDownstreamEvaluator
#    checkpoint_path: *checkpoint_path
#    global_detection: True
#    data_loader:
#      module_name: core.DataLoader
#      class_name: DefaultDataLoader
#      params:
#        args:
#          target_size: *target_size
#          batch_size: *dbatch_size
#          dataset_module:
#            module_name: data.loaders.ixi_loader
#            class_name: IXILoader
#      datasets:
#        Atlas:
#          data_dir:
#            test:
#              - './data/ATLAS/splits/atlas_train_png.csv'
#          label_dir:
#            test:
#              - './data/ATLAS/splits/atlas_train_mask_png.csv'
#
  pseudo_healthy:
    module_name: projects.23_phanes_miccai.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    global_detection: False
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          target_size: *target_size
          batch_size: *dbatch_size
          dataset_module:
            module_name: data.loaders.fastmri_loader
            class_name: FastLoader
      datasets:
        Normal_brain:
          data_dir:
            test:
              - './data/fastMRI/splits/normal_test.csv'