name: MorphAEus_3D
target_size: &target_size !!python/tuple [128, 128, 128]
dbatch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path ./weights/fast_mri/sota/
#
# Experiment
#
experiment:
  name: Morphaeus_trial
  task: train
  weights: #'./weights/fast_mri/sota/2022_11_28_14_46_59_430187/best_model.pt'
#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.morphaeus_3D
  class_name: MorphAEus
  params:
    inshape: *target_size
    bidir: True
    in_channels: 1
    nr_ref_channels: 3
    channels:
      - 1
      - 2
      - 4
      - 8
      - 16
      - 16
      - 16
#      - 256
    strides:
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
#      - 2
    out_ch: 1
    kernel_size: 3
    norm: batch
    act: swish
    deconv_mode: transpose
#
# Trainer
#
trainer:
  module_name: projects.ano_brain.MorphTrainer_3D
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 50
    max_iter: 1500
    loss:
      module_name: optim.losses.ln_losses
      class_name: L2
      params:
    patience: 200
    alfa: 0.2
    # Optimizer
    # Optimizer
    optimizer_params:
#      lr: 1.0e-4 # Orig
      lr: 5.0e-4
  # Data Loader
  data_loader:
# IXI-T1
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.brain3D_loader
          class_name: Brain3DLoader
        data_dir:
          train:
#          - './data/CAPS_IXI/splits/ixi-t1_train_2D.csv'
#          - './data/ATLAS_2/splits/atlas_train_dummy.csv'
          - './data/ADNI/cn_siem_3T_ww_train_.csv'
          val:
#          - './data/ATLAS_2/splits/atlas_test.csv'
#          - './data/CAPS_IXI/splits/ixi-t1_val_2D.csv'
          - './data/ADNI/cn_siem_3T_ww_val_.csv'
          test:
#          - './data/CAPS_IXI/splits/ixi-t1_val_2D.csv'
#            - './data/ATLAS_2/splits/atlas_test_dummy.csv'
          - './data/ADNI/cn_siem_3T_ww_test_.csv'
        target_size: *target_size
#        batch_size: 128 # Orig
        batch_size: 1
# Downstream tasks
downstream_tasks:
    detection:
      module_name: projects.ano_brain.DownstreamEvaluator
      class_name: PDownstreamEvaluator
      checkpoint_path: *checkpoint_path
      global_detection: True
      data_loader:
        module_name: core.DataLoader
        class_name: DefaultDataLoader
        params:
          args:
            target_size: *target_size
            batch_size: *dbatch_size
            dataset_module:
              module_name: data.loaders.brain3D_loader
              class_name: Brain3DLoader
        datasets:
          global_pathology:
            data_dir:
              test:
                - './data/3d_test_data/3d_test_data.csv'
#
# downstream_tasks:
#   detection:
#     module_name: projects.ano_brain.DownstreamEvaluator
#     class_name: PDownstreamEvaluator
#     checkpoint_path: *checkpoint_path
#     data_loader:
#       module_name: core.DataLoader
#       class_name: DefaultDataLoader
#       params:
#         args:
#           target_size: *target_size
#           batch_size: *dbatch_size
#           dataset_module:
#             module_name: data.loaders.fastmri_loader
#             class_name: FastLoader
#       datasets:
#         Normal_brain:
#           data_dir:
#             test:
#               - './data/fastMRI/splits/normal_test.csv'
#         global:
#           data_dir:
#             test:
#               - './data/fastMRI/splits/global.csv'
#         local:
#           data_dir:
#             test:
#               - './data/fastMRI/splits/local.csv'
