name: MorphAEus_alfa_0.0_beta_0.1
target_size: &target_size !!python/tuple [128, 128]
dbatch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path ./weights/fast_mri/sota/
#
# Experiment
#
experiment:
  name: Morphaeus_2D_ADNI_Trials
  task: train
  weights: #'weights/fast_mri/sota/2023_05_22_19_41_58_326024/latest_model.pt'
#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.morphaeus
  class_name: MorphAEus
  params:
    inshape: *target_size
    bidir: True
    in_channels: 1
    nr_ref_channels: 3
    channels:
      - 16
      - 32
      - 64
      - 128
      - 256
      - 256
      - 256
#      - 256
    strides:
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
#      - 2
    out_ch: 1
    kernel_size: 3
    norm: batch
    act: swish
    deconv_mode: transpose
#
# Trainer
#
trainer:
  module_name: projects.ano_brain.MorphTrainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 250
    max_iter: 200
    loss:
      module_name: optim.losses.ln_losses
      class_name: L2
      params:
    patience: 40
    alfa: 0.0
    beta: 0.1
    ncc_window_size: 9
    # Optimizer
    # Optimizer
    optimizer_params:
#      lr: 1.0e-4 # Orig
      lr: 1.0e-3
  # Data Loader
  data_loader:
# IXI-T1
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.loaders.fastmri_loader_2D
          class_name: FastLoader
        data_dir:
          train:
         # - './data/ADNI/adni_female_healthy_2D.csv'
           - './data/ADNI/cn_siem_3T_ww_train_registered_png.csv'
          val:
         # - './data/ADNI/adni_female_AD_2D.csv'
          - './data/ADNI/cn_siem_3T_ww_val_registered_png.csv'
          test:
         # - './data/ADNI/adni_female_AD_2D.csv'
          - './data/ADNI/cn_siem_3T_ww_test_registered_png.csv'
          # - './data/ADNI/AD_Siem_3T_WW_png.csv'
        target_size: *target_size
#        batch_size: 128 # Orig
        batch_size: 8
# Downstream tasks
downstream_tasks:
    detection:
      module_name: projects.ano_brain.DownstreamEvaluator
      class_name: PDownstreamEvaluator
      checkpoint_path: *checkpoint_path
      global_detection: True
      data_loader:
        module_name: core.DataLoader
        class_name: DefaultDataLoader
        params:
          args:
            target_size: *target_size
            batch_size: *dbatch_size
            dataset_module:
              module_name: data.loaders.fastmri_loader_2D
              class_name: FastLoader
        datasets:
          global_detection:
            data_dir:
              test:
                - './data/ADNI/AD_Siem_3T_WW_png.csv'
#
# downstream_tasks:
#   detection:
#     module_name: projects.ano_brain.DownstreamEvaluator
#     class_name: PDownstreamEvaluator
#     checkpoint_path: *checkpoint_path
#     data_loader:
#       module_name: core.DataLoader
#       class_name: DefaultDataLoader
#       params:
#         args:
#           target_size: *target_size
#           batch_size: *dbatch_size
#           dataset_module:
#             module_name: data.loaders.fastmri_loader
#             class_name: FastLoader
#       datasets:
#         Normal_brain:
#           data_dir:
#             test:
#               - './data/fastMRI/splits/normal_test.csv'
#         global:
#           data_dir:
#             test:
#               - './data/fastMRI/splits/global.csv'
#         local:
#           data_dir:
#             test:
#               - './data/fastMRI/splits/local.csv'
