name: SI-VAE
target_size: &target_size !!python/tuple [128, 128]
dbatch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path ./weights/phanes_miccai/sota/
#
# Experiment
#
experiment:
  name: 23_MICCAI_PHANES [Synthetic]
  task: test
  weights:  './weights/fast_mri/sota/2022_11_26_10_31_32_965404/best_model.pt'
#  weights: './weights/phanes_miccai/sota/2023_01_31_16_11_37_011460/latest_model.pt'./weights/fast_mri/sota/2022_11_26_10_31_32_965404

#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.soft_intro_vae_daniel
  class_name: SoftIntroVAE
  params:
    cdim: 1
    zdim: 128
    channels:
      - 64
      - 128
      - 256
      - 512
      - 512
    image_size: 128
    conditional: False
#
# Trainer
#
trainer:
  module_name: projects.23_phanes_miccai.SIVAETrainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 5000
    loss:
      module_name: optim.losses.ln_losses
      class_name: L2
      params:
    # Optimizer
    patience: 500
    optimizer_params:
      lr: 5.0e-5 # 2.0e-4 $ orig
  # Data Loader
  data_loader:
# IXI-T1
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.loaders.ixi_loader
          class_name: IXILoader
        data_dir:
          train:
          - './data/CAPS_IXI/splits/ixi-t1_train_png.csv'
          val:
          - './data/CAPS_IXI/splits/ixi-t1_val_png.csv'
          test:
          - './data/CAPS_IXI/splits/ixi-t1_test_png.csv'
        target_size: *target_size
        batch_size: 8
# Downstream tasks
downstream_tasks:
#  detection:
#    module_name: projects.23_phanes_miccai.DownstreamEvaluator
#    class_name: PDownstreamEvaluator
#    checkpoint_path: *checkpoint_path
#    global_detection: True
#    data_loader:
#      module_name: core.DataLoader
#      class_name: DefaultDataLoader
#      params:
#        args:
#          target_size: *target_size
#          batch_size: *dbatch_size
#          dataset_module:
#            module_name: data.loaders.ixi_loader
#            class_name: IXILoader
#      datasets:
#        Atlas:
#          data_dir:
#            test:
#              - './data/ATLAS/splits/atlas_train_png.csv'
#          label_dir:
#            test:
#              - './data/ATLAS/splits/atlas_train_mask_png.csv'
#
  pseudo_healthy:
    module_name: projects.23_phanes_miccai.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    global_detection: False
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          target_size: *target_size
          batch_size: *dbatch_size
          dataset_module:
            module_name: data.loaders.fastmri_loader
            class_name: FastLoader
      datasets:
        Normal_brain:
          data_dir:
            test:
              - './data/fastMRI/splits/normal_test.csv'