name: VAE
target_size: &target_size !!python/tuple [128, 128]
dbatch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path ./weights/vae_trial/sota/
#
# Experiment
#
experiment:
  name: 23_MICCAI_PHANES [Synthetic]
  task: train
  weights: # './weights/fast_mri/sota/2022_12_05_14_24_26_588331/best_model.pt'
#  weights:  './weights/phanes_miccai/sota/2023_01_31_16_04_55_377770/best_model.pt'

#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#


#
# Model
#
model:
  module_name: model_zoo.vae_hahn
  class_name: VAE
  params:
    input_size: !!python/tuple [1, 128, 128]
    h_size:
      - 16
      - 32
      - 64
      - 256
      - 256 #for input 128, 128
    z_dim: 256
#
# Trainer
#
trainer:
  module_name: projects.ano_brain.Trainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 5000
    patience: 500
    # Loss
    loss:
      module_name: model_zoo.vae_hahn
      class_name: VAELoss
      params:
        rec_log_std: 0
    # Optimizer
    lr_scheduler: 'plateau'
    optimizer_params:
#      lr: 1.0e-4 # Orig
      lr: 5.0e-4
  # Data Loader
  data_loader:
# IXI-T1
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.loaders.fastmri_loader
          class_name: FastLoader
        data_dir:
          train:
#          - './data/CAPS_IXI/splits/ixi-t1_train_2D.csv'
#          - './data/ATLAS_2/splits/atlas_train_dummy.csv'
          - './data/CAPS_IXI/ixi_normal_train.csv'
          val:
#          - './data/ATLAS_2/splits/atlas_test.csv'
#          - './data/CAPS_IXI/splits/ixi-t1_val_2D.csv'
          - './data/fastMRI/normal_val.csv'
          test:
#          - './data/CAPS_IXI/splits/ixi-t1_val_2D.csv'
#            - './data/ATLAS_2/splits/atlas_test_dummy.csv'
          - './data/fastMRI/normal_test.csv'
        target_size: *target_size
        batch_size: 8
# Downstream tasks
downstream_tasks:
#  detection:
#    module_name: projects.23_phanes_miccai.DownstreamEvaluator
#    class_name: PDownstreamEvaluator
#    checkpoint_path: *checkpoint_path
#    global_detection: True
#    data_loader:
#      module_name: core.DataLoader
#      class_name: DefaultDataLoader
#      params:
#        args:
#          target_size: *target_size
#          batch_size: *dbatch_size
#          dataset_module:
#            module_name: data.loaders.ixi_loader
#            class_name: IXILoader
#      datasets:
#        Atlas:
#          data_dir:
#            test:
#              - './data/ATLAS/splits/atlas_train_png.csv'
#          label_dir:
#            test:
#              - './data/ATLAS/splits/atlas_train_mask_png.csv'
#
  pseudo_healthy:
    module_name: projects.ano_brain.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    global_detection: False
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          target_size: *target_size
          batch_size: *dbatch_size
          dataset_module:
            module_name: data.loaders.fastmri_loader
            class_name: FastLoader
      datasets:
        Normal_brain:
          data_dir:
            test:
              - './data/fastMRI/normal_test.csv'