name: ConvAE (Cifar-10)
target_size: &target_size !!python/tuple [64, 64]
train_batch_size: &tbatch_size 16
downstream_batch_size: &dbatch_size 10
checkpoint_path: &checkpoint_path ./projects/rl_project/weights/ACDC/
#
# Experiment
#
experiment:
  name: Rl_project ACDC
  task: train
  weights:  #'./projects/dummy_project/weights/cifar-10/ae/best_model.pt'
#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.vae_hahn
  class_name: ConvAutoEncoder
  params:
    in_channels: 1
    channels:
      - 64
      - 128
    strides:
      - 2
      - 2
      - 2
    out_ch: 1
    kernel_size: 5
    norm: batch
    act: leakyrelu
    deconv_mode: trans
#
# Trainer
#
trainer:
  module_name: projects.dummy_project.Trainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 10
    # Loss
    loss:
      module_name: optim.losses.ln_losses
      class_name: L1
      params:
    optimizer_params:
      lr: 5.0e-4
  # Data Loader
  data_loader:
    module_name: data.ACDC_loader
    class_name: ACDCLoader
    params:
      args:
        root_dir: '/home/iml/maxime.difolco/Documents/data/ACDC/rl_ACDC/rl_maskMyo/'
        csv_file: '/home/iml/maxime.difolco/Documents/data/ACDC/rl_ACDC/data_info_rl_maskMyo.csv'
# Downstream tasks
downstream_tasks:
  cifar10:
    module_name: projects.dummy_project.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    data_loader:
      module_name: data.cifar10_loader
      class_name: Cifar10Loader
      params:
        args:
          target_size: *target_size
          batch_size: *dbatch_size
      datasets:
        dog:
          classes:
            - 'dog'
        car:
          classes:
            - 'car'
        truck:
          classes:
            - 'truck'
